version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: pet-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"            # dev convenience; remove in prod or bind to 127.0.0.1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  server:
    build:
      context: ./server
    container_name: pet-server
    environment:
      # Server listens on 4000 by default (see your code)
      - PORT=4000
      # Internal service name "redis" from this compose file
      - REDIS_URL=redis://redis:6379
      # If you add other envs, put them here or in an .env file
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/healthz',res=>{process.exit(res.statusCode===200?0:1)})"]
      interval: 10s
      timeout: 3s
      retries: 5

  client:
    build:
      context: ./client
      args:
        # This gets baked into the client at build-time (Vite rule)
        VITE_API_BASE: http://localhost:4000
        # If running behind a reverse proxy/ALB later, change to your public API URL
    container_name: pet-client
    ports:
      - "5173:80"              # host:container (nginx serves on 80)
    depends_on:
      server:
        condition: service_healthy
